version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
      - mvn package
      - ls -R
      - mkdir deployment
      - mv target/demo1-0.0.1-SNAPSHOT.jar deployment/demo1-0.0.1-SNAPSHOT.jar
      - cp -R .ebextensions deployment/
      - zip -r spring-app.zip deployment
      - aws s3 cp spring-app.zip s3://spring-webapp-cicd/
artifacts:
  files:
  - spring-app.zip
