version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo In the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - ls -R  # Affiche le contenu pour la vérification

  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r spring-app.zip target/demo1-0.0.1-SNAPSHOT.jar .ebextensions/*
      - ls -R  # Affiche le contenu du dossier après la création du ZIP
      - aws s3 cp spring-app.zip s3://spring-webapp-cicd/spring-app.zip

artifacts:
  files: spring-app.zip
