version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  pre_build:
    commands:
      - echo "Phase de pré-construction"

  build:
    commands:
      - echo "Construction du code"
      - mvn clean install

  post_build:
    commands:
      - echo "Phase post-construction"
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
  discard-paths: yes
