version: 0.2

phases:
 
  pre_build:
    commands:
      - echo In the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - ls -R  # Affiche le contenu pour la vérification

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: 
    - target/demo1-0.0.1-SNAPSHOT.jar
  discard-paths: yes
